# Generated by Django 5.0.2 on 2024-03-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recipie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='recipie_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
